-- 1. Вывести список всех клиентов (customer)
select *
from customer;

-- 2. Вывести список имен и фамилий клиентов с именем Carolyn
select
    first_name,
    last_name
from customer
where first_name = 'Carolyn';

-- 3. Вывести полные имена клиентов (имя + фамилия), имя или фамилия которых содержит “ary”
select
    first_name || ' ' || last_name as full_name
from customer
where first_name ilike '%ary%'
   or last_name  ilike '%ary%';

-- 4. Вывести 20 самых крупных транзакций (payment)
select *
from payment
order by amount desc, payment_date desc, payment_id desc
limit 20;

-- 5. Вывести адреса всех магазинов (подзапрос)
select
    a.address_id,
    a.address
from address a
where a.address_id in (
    select s.address_id
    from store s
)
order by a.address_id;

-- 6. Вывести число, месяц и день недели в числовом эквиваленте
--    (Понедельник = 1, ..., Воскресенье = 7) для каждой оплаты
select
    payment_id,
    extract(day from payment_date)::int   as day_of_month,
    extract(month from payment_date)::int as month_number,
    extract(isodow from payment_date)::int as day_of_week_number
from payment
order by payment_id;

-- 7. Вывести кто, когда и у кого брал диски в аренду в июне 2005 года
select
    customer_id,
    rental_date::date as rental_date,
    staff_id
from rental
where rental_date >= timestamp '2005-06-01'
  and rental_date <  timestamp '2005-07-01'
order by rental_date, customer_id, staff_id;

-- 8. Фильмы после 2000 года, длина 60..120 минут, первые 20 самых длинных
select
    title,
    description,
    length
from film
where release_year > 2000
  and length between 60 and 120
order by length desc, title asc
limit 20;

-- 9. Платежи апреля 2007 <= 4 доллара
select
    payment_id,
    payment_date::date as payment_date,
    amount
from payment
where payment_date >= timestamp '2007-04-01'
  and payment_date <  timestamp '2007-05-01'
  and amount <= 4
order by amount desc, payment_date asc, payment_id asc;

-- 10. Клиенты Jack/Bob/Sara, у которых фамилия содержит букву p
select
    first_name  as "Имя",
    customer_id as "Идентификатор",
    last_name   as "Фамилия"
from customer
where first_name in ('Jack', 'Bob', 'Sara')
  and last_name ilike '%p%'
order by customer_id asc;

-- 11. Таблица студентов
drop table if exists students;

create table students (
    id integer generated by default as identity (start with 52 increment by 1) primary key,
    first_name varchar(100) not null check (btrim(first_name) <> ''),
    last_name varchar(100)  not null check (btrim(last_name) <> ''),
    age integer             not null check (age > 0),
    birth_date date         not null,
    address text            not null check (btrim(address) <> '')
);

-- Внести 1 студента с id > 50
insert into students (id, first_name, last_name, age, birth_date, address)
values (51, 'Иван', 'Петров', 23, date '2001-05-17', 'Москва, ул. Пушкина, д. 10');

-- Посмотреть текущие записи таблицы
select *
from students
order by id;

-- Внести несколько записей 1 запросом, используя автоинкремент id
insert into students (first_name, last_name, age, birth_date, address)
values
    ('Никита', 'Михалков', 80, date '1945-10-21', 'Санкт-Петербург, Невский пр., д. 1'),
    ('Алеша', 'Попович', 24, date '2000-09-03', 'Казань, ул. Ленина, д. 1'),
    ('Оксана', 'Задолбайкина', 21, date '2003-12-01', 'Тула, ул. Мира, д. 15');

-- Посмотреть текущие записи таблицы
select *
from students
order by id;

-- Удалить 1 студента на выбор
delete from students
where id = 52;

-- Вывести полный список студентов
select *
from students
order by id;

-- Удалить таблицу
drop table students;